### ISSUE TITLE
More ease of use

### ISSUE THREAD

**Issue by wow12345678** [neununddreissigzeicheigeBenutzerkennung/TeXperiment#2]
Please add a little Readme with instructions on how to use the feature for compiling the documentation. And maybe a list of functions this package provides. It took me about 15 minutes to understand this by reading the code.

**Comment by neununddreissigzeicheigeBenutzerkennung** [comment]
Sorry for the inconvenience. The README file has been updated to be much more detailled and moved in the main folder. Hopefully this clarifies how to get to documentation. As for listing functions the packages provide. these don't have to do with the documentation directly enough, that it would be hard to list them automatically. I am reluctant to list them manually as I plan to expand on them sooner or later and would probably forget to update the list. 
Thank you for your suggestions for improvement and again sorry for not beeing able to provide the adequate solution for now.

**Comment by wow12345678** [comment]
Thanks!
